#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "agora"
name = "Agora"
description.en = "Software for collaboration and creation of digital space"
description.fr = "Logiciel de collaboration et de création d'espace numérique"

version = "24.2.1~ynh1"

maintainers = ["frju365"]

[upstream]
license = "GPL-2.0-only"
website = "https://www.agora-project.net"
admindoc = "https://www.agora-project.net/index.php?ctrl=offline&action=Documentation"
code = "https://github.com/xech/agora-project"
cpe = "cpe:2.3:a:agora-project:agora-project"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "120M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/agora"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["francais", "english", "espanol"]
    default = "francais"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]
    [resources.sources.main]
    url = "https://github.com/xech/agora-project/archive/refs/tags/24.2.1.tar.gz"
    sha256 = "093ab0bf7950f682d9f72808788e637b4507b6b19315d18e736f56e809efb7bc"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset = "tarball"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "php7.4-fpm",
        "php7.4-imagick",
        "mariadb-server",
    ]

    [resources.database]
    type = "mysql"
