#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "agora"
name = "Agora"
description.en = "Software for collaboration and creation of digital space"
description.fr = "Logiciel de collaboration et de création d'espace numérique"

version = "24.6.3~ynh1"

maintainers = ["frju365"]

[upstream]
license = "GPL-2.0-only"
website = "https://www.agora-project.net"
admindoc = "https://www.agora-project.net/index.php?ctrl=offline&action=Documentation"
code = "https://github.com/xech/agora-project"
cpe = "cpe:2.3:a:agora-project:agora-project"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "120M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/agora"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["francais", "english", "espanol"]
    default = "francais"

    [install.admin]
    type = "user"
    help.en = "The user's main email address will be used for login, not their username."
    help.fr = "L'adresse email principale de ce compte sera utilisée pour la connexion, le nom de compte ne fonctionnera pas."

    [install.password]
    type = "password"

[resources]
    [resources.sources.main]
    url = "https://github.com/xech/agora-project/archive/refs/tags/24.6.3.tar.gz"
    sha256 = "1f0f0a8434d0be534ac67532785672ec3494aa78cebf7bb3dc714f3018636dfa"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset = "tarball"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "php7.4-fpm",
        "php7.4-imagick",
        "mariadb-server",
    ]

    [resources.database]
    type = "mysql"
