#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "agora"
name = "Agora"
description.en = "Collaboration and creation of digital space"
description.fr = "Collaboration et création d'espace numérique"

version = "26.4~ynh1"

maintainers = ["frju365"]

[upstream]
license = "GPL-2.0-only"
website = "https://www.agora-project.net"
admindoc = "https://www.agora-project.net/index.php?ctrl=offline&action=Documentation"
code = "https://github.com/xech/agora-project"
cpe = "cpe:2.3:a:agora-project:agora-project"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "120M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/agora"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["francais", "english", "espanol"]
    default = "francais"

    [install.admin]
    type = "user"
    help.en = "The user's main email address will be used for login, not their username."
    help.fr = "L'adresse email principale de ce compte sera utilisée pour la connexion, le nom de compte ne fonctionnera pas."

    [install.password]
    type = "password"

[resources]
    [resources.sources.main]
    url = "https://github.com/xech/agora-project/archive/refs/tags/26.4.tar.gz"
    sha256 = "b02ce53c7b4136a8bd31b76230303244e76a8dbf0cec43d98a2f24078f525dc4"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset = "tarball"
    
    [resources.sources.install]
    url = "https://github.com/xech/agora-project/releases/download/25.12/INSTALL_agora-project_25.12.4.zip"
    sha256 = "5d7856ee32bea6fe4a77c8bc948a2d73449114c03c2b8b1c3c20f029f486a6b7"
    format = "zip"


    [resources.sources.update]
    url = "https://github.com/xech/agora-project/releases/download/25.12/UPDATE_agora-project_25.12.4.zip"
    sha256 = "de23f0e83ce55960ccaed98be3eeafb756dafc7bad62519b433f7dcfc0a35de8"
    format = "zip"


    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "php8.3-fpm",
        "php8.3-imagick",
        "php8.3-mysql",
        "mariadb-server",
    ]

    [resources.database]
    type = "mysql"
