#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_app_setting_set --key=php_upload_max_filesize --value=1000M

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

admin_lastname=$(ynh_user_get_info "$admin" lastname)
admin_firstname=$(ynh_user_get_info "$admin" firstname)
admin_mail=$(ynh_user_get_info "$admin" mail)

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

#=================================================
# SETUP APPLICATION WITH CURL
#=================================================
ynh_script_progression "Setting up application with CURL..."

ynh_local_curl "/?ctrl=offline&action=install&disconnect=1" \
    "lang=$language" \
    "db_host=localhost" \
    "db_name=$db_name" \
    "db_login=$db_user" \
    "db_password=$db_pwd" \
    "adminName=$admin_lastname" \
    "adminFirstName=$admin_firstname" \
    "adminMailLogin=$admin_mail" \
    "adminPassword=$password" \
    "adminPasswordVerif=$password" \
    "spaceName=YunoHost" \
    "spaceDescription=YunoHost" \
    "spacePublic=0" \
    "spaceDiskLimit=1" \
    "ctrl=offline" \
    "action=install" \
    "formValidate=1" \
    "submit=submit"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
